# Generated by Django 5.2.8 on 2025-11-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Загрузите ваш аватар', null=True, upload_to='users/avatars', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Укажите ваш номер телефона', max_length=35, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='user',
            name='tg_chat_id',
            field=models.CharField(blank=True, help_text='Укажите телеграм chat-id', max_length=50, null=True, verbose_name='Телеграм chat-id'),
        ),
        migrations.AddField(
            model_name='user',
            name='tg_nick',
            field=models.CharField(blank=True, help_text='Укажите ваше имя в телеграмме', max_length=50, null=True, verbose_name='Ник телеграмм'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Укажите ваш Email', max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
