services:
  db:
    image: postgres:15.1-alpine
    env_file:
      - .env
    volumes:
      - pg.data:/var/lib/postgresql/data/
    ports:
      - "${POSTGRES_HOST}:5432"
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  pg_data: