# Generated by Django 5.2.8 on 2025-11-16 14:20

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.TextField(help_text='Укажите место выполнения привычки', verbose_name='Место')),
                ('time', models.TimeField(blank=True, help_text='Укажите время выполнения привычки', null=True, verbose_name='Время')),
                ('action', models.CharField(help_text='Укажите действие, которое представляет собой привычка', max_length=255, verbose_name='Действие')),
                ('pleasant_habit', models.BooleanField(blank=True, default=True, help_text='Привычка, которую можно привязать к выполнению полезной привычки', null=True, verbose_name='Признак приятной привычки')),
                ('periodicity', models.IntegerField(default=1, help_text='Укажите периодичность выполнения привычки(по умолчанию ежедневная)', verbose_name='Периодичность')),
                ('reward', models.CharField(blank=True, help_text='Укажите, чем хотите себя вознаградить после выполнения', max_length=150, null=True, verbose_name='Вознаграждение')),
                ('time_to_complete', models.DurationField(blank=True, default=datetime.timedelta(seconds=120), help_text='Время, которое предположительно потратите', null=True, verbose_name='Время на выполнение')),
                ('is_published', models.BooleanField(blank=True, default=False, help_text='Опубликовать для общего доступа', null=True, verbose_name='Признак публичности')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habit', verbose_name='Связанная привычка')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
